steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/aman-cement-crm', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/aman-cement-crm']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'aman-cement-crm'
    - '--image'
    - 'gcr.io/$PROJECT_ID/aman-cement-crm'
    - '--region'
    - 'asia-southeast1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

images:
- 'gcr.io/$PROJECT_ID/aman-cement-crm'
